### ISSUE TITLE
Configure Amplify to allow roomName as path param

### ISSUE THREAD

**Issue by c-st** [c-st/planning-poker-web#6]
When entering a room name it is added as a path param like so: https://test.planningpoker.cc/Test

Reloading this page currently fails because Amplify doesn't know how to handle the sub path. It should be rewritten to `/`.

**Comment by ejbyne** [comment]
Fixed by https://github.com/c-st/planning-poker-web/commit/ef95ec45c1e68c177edb9ff0b87c819235ca43f4
